spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./src/main/resources/data/db
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enable: true
      path: /h2-console